# These are mostly referenced in head.html
title: "un:Conference Canberra"

# The rest here are Jekyll-specific configs:
baseurl: "" # the subpath of your site, e.g. /blog/
url: ""

markdown: kramdown # the preferred markdown processor

# things that should be excluded from a jekyll build
exclude: [README.md, LICENSE.md, Rakefile, .gitignore, Gemfile, Gemfile.lock, vendor, .asset-cache]

# post permalink URL structure
permalink: /:title

#paginate: 10
