# These are mostly referenced in head.html
title: "un:Conference Canberra"
description: "formerly BarCampCanberra"
hero: >
  A Canberra-born **open web** 'unconference': a con for the *users and
  creators* of an open Internet whose schedule and sessions are filled,
  on-the-day, by its participants.

# Unorganisers list populates html head author meta tag and p in footer include
# - consider moving this into _data?
unorganisers: "klepas, maxious, gavintapp, etc."

# Main contact email given for the site
email: foo@bar.com

# Social media info, linked in the footer
youtube: barcampcanberra
twitter: UnconferenceCBR
facebook: UnConferenceCanberra

# The rest here are Jekyll-specific configs:
baseurl: "" # the subpath of your site, e.g. /blog/
url: ""

markdown: kramdown # the preferred markdown processor

# things that should be excluded from a jekyll build
exclude: [README.md, Rakefile, .gitignore, Gemfile, Gemfile.lock]

# post permalink URL structure
permalink: /:title

#paginate: 10
